package edu.fzu.moodkeeper.dataobject;

import java.util.Date;

public class DiaryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Long diaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.user_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.mood_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Integer moodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.weather_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Integer weatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.category_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_name
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private String diaryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_content
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private String diaryContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_date
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Date diaryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.state
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.anchor
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    private Integer anchor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_id
     *
     * @return the value of diary.diary_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Long getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_id
     *
     * @param diaryId the value for diary.diary_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setDiaryId(Long diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.user_id
     *
     * @return the value of diary.user_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.user_id
     *
     * @param userId the value for diary.user_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.mood_id
     *
     * @return the value of diary.mood_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Integer getMoodId() {
        return moodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.mood_id
     *
     * @param moodId the value for diary.mood_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setMoodId(Integer moodId) {
        this.moodId = moodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.weather_id
     *
     * @return the value of diary.weather_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Integer getWeatherId() {
        return weatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.weather_id
     *
     * @param weatherId the value for diary.weather_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setWeatherId(Integer weatherId) {
        this.weatherId = weatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.category_id
     *
     * @return the value of diary.category_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.category_id
     *
     * @param categoryId the value for diary.category_id
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_name
     *
     * @return the value of diary.diary_name
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public String getDiaryName() {
        return diaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_name
     *
     * @param diaryName the value for diary.diary_name
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setDiaryName(String diaryName) {
        this.diaryName = diaryName == null ? null : diaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_content
     *
     * @return the value of diary.diary_content
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public String getDiaryContent() {
        return diaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_content
     *
     * @param diaryContent the value for diary.diary_content
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setDiaryContent(String diaryContent) {
        this.diaryContent = diaryContent == null ? null : diaryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_date
     *
     * @return the value of diary.diary_date
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Date getDiaryDate() {
        return diaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_date
     *
     * @param diaryDate the value for diary.diary_date
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setDiaryDate(Date diaryDate) {
        this.diaryDate = diaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.state
     *
     * @return the value of diary.state
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.state
     *
     * @param state the value for diary.state
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.anchor
     *
     * @return the value of diary.anchor
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public Integer getAnchor() {
        return anchor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.anchor
     *
     * @param anchor the value for diary.anchor
     *
     * @mbg.generated Mon May 10 17:08:35 CST 2021
     */
    public void setAnchor(Integer anchor) {
        this.anchor = anchor;
    }
}